### ISSUE TITLE
Pre-trained model

### ISSUE THREAD

**Issue by SanthoshRajendiran** [hyperconnect/MMNet#1]
We went through your model. The outputs were surprising. Could you share with us your pre-trained model? Is the model giving these results in Mobile CPU?? You have handled quantized models, but how did you manage to preserve the accuracy to good extent.

**Comment by shurain-hpcnt** [comment]
> Could you share with us your pre-trained model?

We don't have a plan to release a pre-trained model yet.

> Is the model giving these results in Mobile CPU??

Yes, the model is intended to work best on mobile CPUs. To reduce latency, we had to implement custom operations that support SIMD instructions.

> You have handled quantized models, but how did you manage to preserve the accuracy to good extent.

As mentioned in the supplementary material, we've used fake quantization for quantization-aware training.
