### ISSUE TITLE
what is depth_multiplier?

### ISSUE THREAD

**Issue by pourfard** [hyperconnect/MMNet#3]
Hi,
I see in the paper that higher depth multiplier (0.5, 0.75, 1.0) leads to lower gradient error. My question is what is it and how much i can increase it?

**Comment by shurain** [comment]
Refer to [MobileNets: Efficient Convolutional Neural Networks for Mobile Vision Applications](https://arxiv.org/abs/1704.04861) for the explanation of width multipliers. Basically, it scales the number of channels which, in turn, changes the capacity of the model. You can increase it as much as you want but increasing it will make your network slower and bulkier.
