### ISSUE TITLE
where model

### ISSUE THREAD

**Issue by sharonjunjun** [hyperconnect/MMNet#5]
Can you tell me where model is if i want to run demo?

**Comment by shurain** [comment]
We do not provide pre-trained models. You'll have to train your own model using the data provided by the authors of "Deep Automatic Portrait Matting" at [http://xiaoyongshen.me/webpages/webpage_automatting/](http://xiaoyongshen.me/webpages/webpage_automatting/)

**Comment by sharonjunjun** [comment]
ok,i'm try.thanks


------------------ 原始邮件 ------------------
发件人: "Sungjoo Ha"<notifications@github.com>;
发送时间: 2019年5月29日(星期三) 下午5:19
收件人: "hyperconnect/MMNet"<MMNet@noreply.github.com>;
抄送: "sharon"<296865232@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [hyperconnect/MMNet] where model (#5)




We do not provide pre-trained models. You'll have to train your own model using the data provided by the authors of "Deep Automatic Portrait Matting" at http://xiaoyongshen.me/webpages/webpage_automatting/
